#pragma once

#include <cstdint>

#include "dap_constants.hpp"
#include "dap_io.hpp"
#include "libxr.hpp"

namespace DAP
{

// DAP Protocol Constants
constexpr uint16_t kMaxRequestSize = 512;
constexpr uint16_t kMaxResponseSize = 512;
constexpr uint16_t kDefaultRetryCount = 100;
constexpr uint8_t kDefaultIdleCycles = 0;

enum class DapPort : uint8_t
{
  DISABLED = 0,
  SWD = 1,
  JTAG = 2
};

// DAP (Debug Access Port) Protocol Handler
class DapProtocol
{
 public:
  explicit DapProtocol(DapIo& io);

  /**
   * @brief Execute DAP command
   * @param request Pointer to request buffer (contains command ID and parameters)
   * @param response_callback Callback to send response data
   * @return Total response length in bytes
   */
  uint32_t ExecuteCommand(const uint8_t* request,
                          LibXR::Callback<const uint8_t*, size_t> response_callback);

  void Reset();

  DapPort GetDebugPort() const { return state_.debug_port; }

 private:

  struct TransferConfig
  {
    uint8_t idle_cycles = kDefaultIdleCycles;
    uint16_t retry_count = kDefaultRetryCount;
    uint16_t match_retry = 0;
    uint32_t match_mask = 0;
  };

  struct SwdConfig
  {
    uint8_t turnaround = 1;
    bool data_phase = false;
  };

  struct State
  {
    DapPort debug_port = DapPort::DISABLED;
    volatile bool transfer_abort = false;
    TransferConfig transfer_config;
    SwdConfig swd_config;
  };

  struct CommandResult
  {
    uint16_t request_consumed = 0;
    uint16_t response_generated = 0;
  };

  // Core Processing

  void Setup();

  /**
   * @brief Processes a DAP command and generates response.
   * @param request Pointer to request buffer containing command and parameters.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   */
  CommandResult ProcessCommand(const uint8_t* request,
                               LibXR::Callback<const uint8_t*, size_t> response_callback);

  // Command Handlers

  /**
   * @brief Handles DAP_Info command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x00] [Info_ID]
   * Response format: [Status] [Info_data...]
   */
  CommandResult HandleInfo(const uint8_t* req,
                           LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_HostStatus command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x01] [Status] [0=Connect/1=Running]
   * Response format: [0x00=DAP_OK]
   */
  CommandResult HandleHostStatus(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_Connect command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x02] [Port=0=Default/1=SWD/2=JTAG]
   * Response format: [Port_status=0=Failed/1=SWD/2=JTAG]
   */
  CommandResult HandleConnect(const uint8_t* req,
                              LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_Disconnect command requests.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x03]
   * Response format: [Status=0x00=DAP_OK]
   */
  CommandResult HandleDisconnect(
      LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_TransferConfigure command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x04] [Idle_cycles] [Retry_count(L)] [Retry_count(H)] [Match_retry(L)] [Match_retry(H)]
   * Response format: [0x00=DAP_OK]
   */
  CommandResult HandleTransferConfigure(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_Transfer command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x05] [DAP_index] [Transfer_count] [Transfer_requests...]
   * Response format: [Transfer_count] [Response_data...] [Status]
   */
  CommandResult HandleTransfer(const uint8_t* req,
                               LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_TransferBlock command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x06] [DAP_index] [Transfer_count(L)] [Transfer_count(H)] [Transfer_request] [Data...]
   * Response format: [Transfer_count(L)] [Transfer_count(H)] [Response_data...] [Status]
   */
  CommandResult HandleTransferBlock(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_ResetTarget command requests.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x0A]
   * Response format: [Status=0x00=DAP_OK]
   */
  CommandResult HandleResetTarget(
      LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_SWJ_Pins command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x10] [Pin_select] [Pin_values] [Wait_time(L)] [Wait_time(H)]
   * Response format: [Pin_values]
   */
  CommandResult HandleSwjPins(const uint8_t* req,
                              LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_SWJ_Clock command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x11] [Clock(L)] [Clock(H)]
   * Response format: [0x00=DAP_OK]
   */
  CommandResult HandleSwjClock(const uint8_t* req,
                               LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_SWJ_Sequence command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x12] [Bit_count] [Sequence_data...]
   * Response format: [0x00=DAP_OK]
   */
  CommandResult HandleSwjSequence(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_SWD_Configure command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x13] [Turnaround] [Data_phase]
   * Response format: [0x00=DAP_OK]
   */
  CommandResult HandleSwdConfigure(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  /**
   * @brief Handles DAP_SWD_Sequence command requests.
   * @param req Pointer to request buffer.
   * @param response_callback Callback to send response data.
   * @return CommandResult with request consumed and response generated bytes.
   *
   * Command format: [0x1D] [Sequence_count] [Sequence_info...] [Sequence_data...]
   * Response format: [Sequence_count] [Sequence_info...] [Response_data...]
   */
  CommandResult HandleSwdSequence(
      const uint8_t* req, LibXR::Callback<const uint8_t*, size_t> response_callback);

  
  
  // Prevent copying
  DapProtocol(const DapProtocol&) = delete;
  DapProtocol& operator=(const DapProtocol&) = delete;

 private:
  LibXR::ErrorCode SetupSwd();
  LibXR::ErrorCode SetupJtag();
  void PortOff();

  DapIo& io_;
  State state_;

  using InfoHandler = std::function<uint8_t(uint8_t* response_data_buffer)>;
  struct InfoEntry
  {
    InfoId id;
    InfoHandler handler;
  };
};

}  // namespace DAP
